# name: 构建并推送镜像到腾讯云镜像仓库

# on:
#   push:
#     branches:
#       - main   

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: 检查代码
#         uses: actions/checkout@v3

#       - name: 安装 qemu
#         uses: docker/setup-qemu-action@v3

#       - name: 安装 Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: 登录腾讯云镜像仓库
#         uses: docker/login-action@v3
#         with:
#           registry: ${{ secrets.TENCENT_REGISTRY_NAME }}
#           username: ${{ secrets.TENCENT_REGISTRY_USER }}
#           password: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}

#       - name: 构建并推送镜像到腾讯云镜像仓库
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           push: true
#           tags: ${{ secrets.TENCENT_REGISTRY_NAME }}/${{ secrets.TENCENT_REGISTRY_HUB }}/durian-xiuxian:latest
#           platforms: linux/amd64

#       - name: 部署到服务器
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           port: 22
#           script: |
#             cd ${{ secrets.SERVER_TARGET_DIR }}
#             docker compose up -d